name: time_tracker
description: 时间追踪 - 温和的人生记录器
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  provider: ^6.1.1
  intl: ^0.19.0
  fl_chart: ^0.66.2
  excel: ^4.0.0
  path_provider: ^2.1.2
  share_plus: ^6.3.4
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "app_icon.png"
  adaptive_icon_background: "#F5F0EB"
  adaptive_icon_foreground: "app_icon.png"
